version: '3'
services:
  db:
    container_name: data-heros
    image: postgres:latest
    ports:
    - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hero

  app:
    container_name: heros
    build: ./hero-api
    working_dir: /hero-api
    volumes:
      - ./hero-api:/hero-api
      - ~/.m2:/root/.m2
    ports:
    - "9090:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hero
      - SPRING_DATASOURCE_USERNAMEe=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=hero
