version: '3'
services:
  web-personas:
    container_name: heros
    build: ./hero-api
    ports: ["8080:8080"]
    links:
      - db
    environment:
      - server.port=8080
      - spring.datasource.url=jdbc:postgresql://data-pg:5432/hero
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
#  app:
#    container_name: app-angular
#    build: ./hero-front-end
#    ports: ["4200:4200"]
  db:
    container_name: data-heros
    image: postgres:latest
    ports: ["5433:5432"]
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hero